version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: waste-collection-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - waste-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waste-collection-app
    depends_on:
      - mongodb
    volumes:
      - .:/var/www
    networks:
      - waste-network
  
  mongodb:
    image: mongo:6.0
    container_name: waste-collection-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: waste_collection
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - waste-network

volumes:
  mongodb_data:

networks:
  waste-network:
    driver: bridge
