version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: waste-collection-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: waste_collection
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - waste-network

volumes:
  mongodb_data:

networks:
  waste-network:
    driver: bridge
